apiVersion: v2
name: homyak
description: A Helm chart for homyak application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - homyak
  - go
maintainers:
  - name: Victor Zhuk
    email: iam@victorzh.uk
